### ISSUE TITLE
Is it necessary to specify the bootstrap version in _pkgdown.yml?

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/poissontemplate#8]
ie 

```
template:
  bootstrap: 5
  package: poissontemplate
```

vs

```
template:
  package: poissontemplate
```

**Comment by joethorley** [comment]
I ask because the pkgdown documentation on template packages states that

<img width="834" alt="Screenshot 2025-01-07 at 09 11 18" src="https://github.com/user-attachments/assets/219b6947-6900-4bfb-a57c-9cb7a03a4f61" />

and in inst/pkgdown/_pkgdown.yml you set

```
template:
  bootstrap: 5
  bslib:
    primary: "#255783"
    navbar-light-color: "#255783"
    base_font: {google: "Roboto Condensed"}
    heading_font: {google: "Playfair Display"}
    code_font: {google: "Roboto Mono"}
  math-rendering: katex
...
```
